### ISSUE TITLE
Translate: the `get_started` chapter

### ISSUE THREAD

**Issue by zdying** [hiproxy/hiproxy.org#1]
I will translate the all the `get_started` chapter.

include:

* applied_to_existing_projects.md
* cli_options.md
* installation.md
* introduction.md
* run_example.md

**Comment by Jeoxs** [comment]
Hey @zdying! Which part would you like me to help you translating?

**Comment by zdying** [comment]
@Jeoxs My friend is translating the get started chapter. You can choose any chapter you like to do it

Thank you so much:)
